// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisLabTopo.Data;

#nullable disable

namespace SisLabTopo.Data.Migrations
{
    [DbContext(typeof(SisLabTopoDbContext))]
    [Migration("20260720061448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SisLabTopo.Data.Entities.AppState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HoraBloqueoUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppState", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IntentosFallidos = 0
                        });
                });

            modelBuilder.Entity("SisLabTopo.Data.Entities.ConfigEntry", b =>
                {
                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Clave");

                    b.ToTable("ConfigEntries", (string)null);
                });

            modelBuilder.Entity("SisLabTopo.Domain.Models.DetallePrestamo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Devuelto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacionItem")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrestamoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipoCodigo");

                    b.HasIndex("PrestamoId");

                    b.ToTable("DetallesPrestamo", (string)null);
                });

            modelBuilder.Entity("SisLabTopo.Domain.Models.Equipo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Denominacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Serie")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("SisLabTopo.Domain.Models.Prestamo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoEstudiante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Docente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEstudiante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prestamos", (string)null);
                });

            modelBuilder.Entity("SisLabTopo.Domain.Models.DetallePrestamo", b =>
                {
                    b.HasOne("SisLabTopo.Domain.Models.Equipo", "Equipo")
                        .WithMany("DetallesPrestamo")
                        .HasForeignKey("EquipoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisLabTopo.Domain.Models.Prestamo", "Prestamo")
                        .WithMany("Detalles")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("SisLabTopo.Domain.Models.Equipo", b =>
                {
                    b.Navigation("DetallesPrestamo");
                });

            modelBuilder.Entity("SisLabTopo.Domain.Models.Prestamo", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
